### ISSUE TITLE
Compile a safe version of `jq` to run in `jqplay`

### ISSUE THREAD

**Issue by jingweno** [jingweno/jqplay#48]
`jq` 1.5 can get the env var: https://github.com/stedolan/jq/blob/jq-1.5/builtin.c#L1291. We'd need to compile a version of `jq` that is safe to run on `jqplay`.

@nicowilliams Any ideas I could do that?

**Comment by nicowilliams** [comment]
Is the environment not safe?  Well, you could prefix `def env: null;` to all user programs, for one (this wouldn't work apply to modules, but you probably have none to load in the jqplay environment).

You could also run the jq executable with no environment.  This seems safest.  jq itself won't need anything from the environment.

**Comment by jingweno** [comment]
> Well, you could prefix def env: null;

Could you elaborate more?

> You could also run the jq executable with no environment. This seems safest. jq itself won't need anything from the environment.

How would I do that?

**Comment by nicowilliams** [comment]
Surely Go has a way to start a process with a specific environment?

Anyways, prefixing the jq program with `def env: null; ` will cause any calls to `env` to bind to that function, so that's a possible bandaid, but errors will have the wrong line and column numbers.  I think it's best if you figure out how to spawn child processes with specific environments in Go.

**Comment by jingweno** [comment]
> Surely Go has a way to start a process with a specific environment?

Gotcha. I fixed it in https://github.com/jingweno/jqplay/pull/49.
